### ISSUE TITLE
AttributeError: 'StableDiffusionXLPipelineOutput' object has no attribute 'permute'

### ISSUE THREAD

**Issue by O-O1024** [tanglaoya321/ComfyUI-StoryMaker#3]
```
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/ComfyUI/custom_nodes/ComfyUI-StoryMaker/nodes.py", line 152, in generate
    output = output.permute(0, 2, 3, 1)
AttributeError: 'StableDiffusionXLPipelineOutput' object has no attribute 'permute'
```

**Comment by tanglaoya321** [comment]
I missed a submission earlier, but I've submitted it now.
