### ISSUE TITLE
TypeError,maybe mask_image is the problem?

### ISSUE THREAD

**Issue by zzddwyff** [tanglaoya321/ComfyUI-StoryMaker#5]
got prompt
Final image size: <PIL.Image.Image image mode=RGB size=1024x1280 at 0x7FEB086BDD80>
Final image size: <PIL.Image.Image image mode=RGB size=720x720 at 0x7FEB086BD8A0>
!!! Exception during processing !!! 
Traceback (most recent call last):
  File "/root/autodl-tmp/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-StoryMaker/nodes.py", line 128, in generate
    face_info = self.get_face_info(image)
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-StoryMaker/nodes.py", line 104, in get_face_info
    face_info = self.shared.app.get(cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR))
  File "/root/autodl-tmp/conda/envs/py310/lib/python3.10/site-packages/insightface/app/face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "/root/autodl-tmp/conda/envs/py310/lib/python3.10/site-packages/insightface/model_zoo/retinaface.py", line 224, in detect
    scores_list, bboxes_list, kpss_list = self.forward(det_img, self.det_thresh)
  File "/root/autodl-tmp/conda/envs/py310/lib/python3.10/site-packages/insightface/model_zoo/retinaface.py", line 194, in forward
    bboxes = distance2bbox(anchor_centers, bbox_preds)
  File "/root/autodl-tmp/conda/envs/py310/lib/python3.10/site-packages/insightface/model_zoo/retinaface.py", line 38, in distance2bbox
    x1 = points[:, 0] - distance[:, 0]
  File "/root/autodl-tmp/conda/envs/py310/lib/python3.10/site-packages/numpy/_core/_internal.py", line 876, in array_ufunc_errmsg_formatter
    args_string = ', '.join(['{!r}'.format(arg) for arg in inputs] +
  File "/root/autodl-tmp/conda/envs/py310/lib/python3.10/site-packages/numpy/_core/_internal.py", line 876, in <listcomp>
    args_string = ', '.join(['{!r}'.format(arg) for arg in inputs] +
  File "/root/autodl-tmp/conda/envs/py310/lib/python3.10/site-packages/numpy/_core/arrayprint.py", line 1578, in _array_repr_implementation
    skipdtype = dtype_is_implied(arr.dtype) and arr.size > 0
  File "/root/autodl-tmp/conda/envs/py310/lib/python3.10/site-packages/numpy/_core/arrayprint.py", line 1514, in dtype_is_implied
    dtype = np.dtype(dtype)
TypeError

**Comment by tanglaoya321** [comment]
I don't think this is an issue with mask_image, because the problem occurs in this line of code: 
`face_info = self.get_face_info(image). `
This line doesn't use mask_image. Could you try a different image? Maybe this one can't detect a face.

**Comment by zzddwyff** [comment]
> I don't think this is an issue with mask_image, because the problem occurs in this line of code: `face_info = self.get_face_info(image). ` This line doesn't use mask_image. Could you try a different image? Maybe this one can't detect a face.

I have changed the example image , but did not work,I find that the problem is in insightface,my insightface is 0.7.3 ,what about you?

**Comment by tanglaoya321** [comment]
My insightface is also 0.7.3

**Comment by zzddwyff** [comment]
> My insightface is also 0.7.3

I am confuse now and i don't know what happen,what else did you do to those model?
